# Generated by Django 3.1.5 on 2022-02-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220209_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_article_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
