# Generated by Django 3.1.5 on 2022-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_main_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_blur_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
