# Generated by Django 3.1.5 on 2022-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='map_adress_link',
            field=models.URLField(default='', max_length=500),
        ),
    ]
