# Generated by Django 3.1.5 on 2022-02-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_contactinfo_map_adress_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
    ]
