# Generated by Django 3.1.5 on 2022-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20220211_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
