# Generated by Django 3.1.5 on 2022-02-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_message_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='map_adress_link',
            new_name='map_address_link',
        ),
    ]
