# Generated by Django 3.1.5 on 2022-02-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220222_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
